In [1]:
import pandas as pd
import openpyxl

In [23]:
base_path = "C:\\Users\\MASTER\\Desktop\\교통데이터"

file_path = base_path + f"\\이용량 지표(목적통행량)_20240513 ({i}).xlsx"

In [25]:
# 해당 코드는 교통카드 빅데이터 시스템에서 22년 1월 1일부터 24년 5월 1일까지의 데이터를 다운로드하여 정제하였다.


file_paths = []


# 파일 경로 설정
for i in range(89):
    file_paths.append(f"C:\\Users\\MASTER\\Desktop\\교통데이터\\이용량 지표(목적통행량)_20240513 ({i}).xlsx")

# 모든 파일을 읽어 하나의 데이터프레임으로 합치기
df_combined = pd.concat([pd.read_excel(fp) for fp in file_paths], ignore_index=True)

In [122]:
# 모든 값이 nan인 열 삭제
df_cleaned = df.dropna(axis=1, how='all')

In [123]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164181 entries, 2452 to 166632
Data columns (total 55 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   시간대:         164181 non-null  object
 1   Unnamed: 1   164181 non-null  object
 2   Unnamed: 2   164181 non-null  object
 3   Unnamed: 3   164181 non-null  object
 4   Unnamed: 4   164181 non-null  object
 5   합계           164181 non-null  object
 6   04           164181 non-null  object
 7   05           164181 non-null  object
 8   06           164181 non-null  object
 9   07           164181 non-null  object
 10  08           164181 non-null  object
 11  09           164181 non-null  object
 12  10           164181 non-null  object
 13  11           164181 non-null  object
 14  12           164181 non-null  object
 15  13           164181 non-null  object
 16  14           164181 non-null  object
 17  15           164181 non-null  object
 18  16           164181 non-null  object
 19  17           164181 non-null  object
 20  18           164181 non-null  object
 21  19           164181 non-null  object
 22  20           164181 non-null  object
 23  21           164181 non-null  object
 24  22           164181 non-null  object
 25  23           164181 non-null  object
 26  00           164181 non-null  object
 27  01           164181 non-null  object
 28  02           164181 non-null  object
 29  03           164181 non-null  object
 30  Unnamed: 6   164181 non-null  object
 31  Unnamed: 8   164181 non-null  object
 32  Unnamed: 10  164181 non-null  object
 33  Unnamed: 12  164181 non-null  object
 34  Unnamed: 14  164181 non-null  object
 35  Unnamed: 16  164181 non-null  object
 36  Unnamed: 18  164181 non-null  object
 37  Unnamed: 20  164181 non-null  object
 38  Unnamed: 22  164181 non-null  object
 39  Unnamed: 24  164181 non-null  object
 40  Unnamed: 26  164181 non-null  object
 41  Unnamed: 28  164181 non-null  object
 42  Unnamed: 30  164181 non-null  object
 43  Unnamed: 32  164181 non-null  object
 44  Unnamed: 34  164181 non-null  object
 45  Unnamed: 36  164181 non-null  object
 46  Unnamed: 38  164181 non-null  object
 47  Unnamed: 40  164181 non-null  object
 48  Unnamed: 42  164181 non-null  object
 49  Unnamed: 44  164181 non-null  object
 50  Unnamed: 46  164181 non-null  object
 51  Unnamed: 48  164181 non-null  object
 52  Unnamed: 50  164181 non-null  object
 53  Unnamed: 52  164181 non-null  object
 54  Unnamed: 54  164181 non-null  object
dtypes: object(55)
memory usage: 68.9+ MB

In [124]:
# 컬럼 재설정
columns_list = ["시도코드", "시도", "시군구", "일", "이용자유형", "총 발생량", "04시 발생량", "05시 발생량", "06시 발생량", "07시 발생량", "08시 발생량", "09시 발생량", "10시 발생량", "11시 발생량", "12시 발생량", "13시 발생량", "14시 발생량", "15시 발생량", "16시 발생량", "17시 발생량", "18시 발생량", "19시 발생량", "20시 발생량", "21시 발생량", "22시 발생량", "23시 발생량", "00시 발생량", "01시 발생량", "02시 발생량", "03시 발생량", "총 도착량", "04시 도착량", "05시 도착량", "06시 도착량", "07시 도착량", "08시 도착량", "09시 도착량", "10시 도착량", "11시 도착량", "12시 도착량", "13시 도착량", "14시 도착량", "15시 도착량", "16시 도착량", "17시 도착량", "18시 도착량", "19시 도착량", "20시 도착량", "21시 도착량", "22시 도착량", "23시 도착량", "00시 도착량", "01시 도착량", "02시 도착량", "03시 도착량"]

In [125]:
# 컬럼 변경
df_cleaned.columns = columns_list

In [126]:
df_cleaned

,시도코드,시도,시군구,일,이용자유형,총 발생량,04시 발생량,05시 발생량,06시 발생량,07시 발생량,...,18시 도착량,19시 도착량,20시 도착량,21시 도착량,22시 도착량,23시 도착량,00시 도착량,01시 도착량,02시 도착량,03시 도착량
2452,시도코드,시도,시군구,일,이용자유형,발생량,발생량,발생량,발생량,발생량,...,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량
2453,합계,0,0,0,0,114284606,368328,1565950,3060455,7517612,...,9907629,7500880,4900361,4349626,4014120,2411732,858761,130804,62462,53811
2454,11,서울특별시,강남구,2024-04-15(월),경로,84187,76,915,2182,2305,...,3194,2103,1517,1163,646,282,86,8,9,20
2455,0,0,0,0,국가유공자,1275,1,14,50,48,...,78,46,31,17,16,9,4,1,0,0
2456,0,0,0,0,어린이,5913,0,0,13,202,...,735,498,260,213,247,19,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166628,0,0,0,0,어린이,666,0,1,0,5,...,58,33,25,25,8,9,1,0,0,0
166629,0,0,0,0,외국인,15,0,2,0,1,...,0,0,0,0,1,0,0,0,0,0
166630,0,0,0,0,일반인,63378,348,989,1432,2218,...,4986,3944,3459,4857,3192,1595,424,45,16,15
166631,0,0,0,0,장애인,1628,1,76,43,47,...,102,84,65,60,45,25,2,0,0,0
166632,0,0,0,0,청소년,2329,0,4,15,21,...,205,193,142,206,149,72,9,0,0,0

In [77]:
# 아래의 데이터의 경우 엑셀에서의 인덱스 데이터와 합계 데이터이다.
df[(df['시도코드'] == "시도코드") | (df['시도코드'] == "합계")]

,시도코드,시도,시군구,일,이용자유형,총 발생량,04시 발생량,05시 발생량,06시 발생량,07시 발생량,...,18시 도착량,19시 도착량,20시 도착량,21시 도착량,22시 도착량,23시 도착량,00시 도착량,01시 도착량,02시 도착량,03시 도착량
2452,시도코드,시도,시군구,일,이용자유형,발생량,발생량,발생량,발생량,발생량,...,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량
2453,합계,0,0,0,0,114284606,368328,1565950,3060455,7517612,...,9907629,7500880,4900361,4349626,4014120,2411732,858761,130804,62462,53811
4904,시도코드,시도,시군구,일,이용자유형,발생량,발생량,발생량,발생량,발생량,...,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량
4905,합계,0,0,0,0,27580927,92175,383599,806921,2081955,...,2490578,1889323,1175434,1027325,943301,570144,227386,34680,15943,13069
5431,시도코드,시도,시군구,일,이용자유형,발생량,발생량,발생량,발생량,발생량,...,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161202,합계,0,0,0,0,88562435,282611,1186252,2262949,5601198,...,8040081,6160762,3713204,4566895,2758253,1088839,194602,29208,14514,14098
163654,시도코드,시도,시군구,일,이용자유형,발생량,발생량,발생량,발생량,발생량,...,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량
163655,합계,0,0,0,0,93488514,288086,1225427,2319299,5693894,...,8183402,6216581,3852228,4866102,2947593,1149183,206649,30819,14998,14362
166106,시도코드,시도,시군구,일,이용자유형,발생량,발생량,발생량,발생량,발생량,...,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량
166107,합계,0,0,0,0,10329768,21449,121360,179210,256548,...,692188,500974,421821,592681,357187,149929,27161,3662,1702,1443

In [81]:
# 위의 데이터는 필요 없으므로 제거
clean_df =  df[~((df['시도코드'] == "시도코드") | (df['시도코드'] == "합계"))]

In [88]:
clean_df = clean_df.iloc[:,2:]

In [93]:
clean_df[50:100]

,시군구,일,이용자유형,총 발생량,04시 발생량,05시 발생량,06시 발생량,07시 발생량,08시 발생량,09시 발생량,...,18시 도착량,19시 도착량,20시 도착량,21시 도착량,22시 도착량,23시 도착량,00시 도착량,01시 도착량,02시 도착량,03시 도착량
2504,0,0,국가유공자,1327,0,18,37,54,75,72,...,74,44,27,18,18,8,1,0,1,0
2505,0,0,어린이,6135,0,3,12,199,542,36,...,724,484,296,246,262,10,2,0,0,0
2506,0,0,외국인,1258,0,0,1,10,20,42,...,92,91,65,48,45,15,5,0,0,0
2507,0,0,일반인,767733,629,3181,10019,26765,33415,22644,...,48834,33016,19065,15698,13733,7408,2911,481,255,279
2508,0,0,장애인,15869,28,173,364,591,773,712,...,760,517,334,235,172,88,39,5,3,3
2509,0,0,청소년,29838,1,33,310,3844,1130,269,...,1984,1316,834,942,1994,468,114,14,6,2
2510,0,2024-04-23(화),경로,90147,82,1073,2354,2469,3515,4782,...,3644,2360,1737,1240,697,290,92,6,5,18
2511,0,0,국가유공자,1344,1,21,39,47,89,64,...,82,37,49,27,19,10,6,0,0,0
2512,0,0,어린이,6290,0,4,12,220,385,34,...,807,524,243,207,275,12,1,0,0,0
2513,0,0,외국인,1337,0,2,9,7,19,34,...,95,74,67,38,34,32,7,0,0,0
2514,0,0,일반인,801176,811,3330,10020,27451,33559,23375,...,51820,35257,19417,16277,14982,7656,2892,522,240,288
2515,0,0,장애인,16054,24,174,400,571,754,760,...,773,516,332,220,171,87,32,7,5,3
2516,0,0,청소년,29616,2,32,298,3818,1026,449,...,1843,1368,1048,963,1877,408,92,19,2,0
2517,0,2024-04-24(수),경로,87781,86,1010,2296,2245,3073,4455,...,3642,2406,1802,1386,817,343,114,8,7,12
2518,0,0,국가유공자,1391,1,11,40,64,66,62,...,85,57,27,26,23,7,5,1,0,0
2519,0,0,어린이,6499,0,2,13,157,610,210,...,709,472,280,254,167,8,2,0,0,0
2520,0,0,외국인,1484,0,3,2,14,31,42,...,105,95,70,65,74,34,6,0,0,0
2521,0,0,일반인,795477,775,3220,9696,26697,34295,23555,...,52919,35352,19828,17396,15952,8712,3241,596,295,313
2522,0,0,장애인,15788,32,178,394,606,752,689,...,742,556,380,285,221,103,44,6,8,3
2523,0,0,청소년,31737,1,33,267,3356,1325,1369,...,1844,1544,956,862,1721,409,113,14,0,2
2524,0,2024-04-25(목),경로,91027,89,1083,2278,2350,3324,4880,...,3750,2576,1944,1498,816,359,119,13,6,16
2525,0,0,국가유공자,1451,2,21,35,53,73,76,...,101,41,39,26,19,13,2,1,0,0
2526,0,0,어린이,6858,0,2,14,179,616,257,...,826,545,272,275,288,11,3,0,0,0
2527,0,0,외국인,1481,0,1,4,7,18,38,...,125,107,77,54,57,25,12,0,0,0
2528,0,0,일반인,813319,861,3377,9579,26542,33221,23705,...,55641,36453,20754,17892,16601,9531,3892,661,356,317
2529,0,0,장애인,16494,29,178,406,601,746,729,...,823,518,370,296,203,122,40,11,3,1
2530,0,0,청소년,33693,0,28,287,3398,1246,2334,...,1996,1338,892,914,1606,439,129,22,5,3
2531,0,2024-04-26(금),경로,92327,76,1090,2298,2311,3302,4856,...,3828,2601,2022,1481,943,410,125,5,4,8
2532,0,0,국가유공자,1415,3,14,44,55,69,81,...,90,57,43,22,18,12,6,0,0,0
2533,0,0,어린이,7341,0,5,9,242,724,62,...,808,600,304,307,304,15,7,0,0,0
2534,0,0,외국인,1559,0,1,5,15,26,57,...,110,110,69,49,48,41,20,1,0,0
2535,0,0,일반인,834842,908,3296,9581,25238,31661,23382,...,64120,41411,22277,18385,18102,11350,5370,794,374,304
2536,0,0,장애인,16659,30,194,373,589,784,741,...,858,573,345,272,230,119,57,13,4,4
2537,0,0,청소년,36054,1,35,301,3202,1355,2105,...,2269,1515,1040,1102,1884,536,202,28,5,5
2538,0,2024-04-27(토),경로,60966,46,983,2033,1781,2578,3681,...,2833,2112,1900,1324,686,345,52,3,1,2
2539,0,0,국가유공자,905,1,15,23,27,31,62,...,59,32,29,31,14,10,4,0,1,0
2540,0,0,어린이,8809,1,9,15,41,180,449,...,556,342,259,208,119,19,3,0,0,0
2541,0,0,외국인,1569,0,4,3,13,19,52,...,147,115,83,69,42,44,1,0,0,0
2542,0,0,일반인,531218,795,3091,4673,8151,12856,16273,...,32655,21935,17795,17330,13868,10064,3000,556,245,230
2543,0,0,장애인,10514,21,157,330,275,418,552,...,525,394,311,246,153,82,21,5,6,2
2544,0,0,청소년,28367,8,47,63,194,460,907,...,1747,1224,917,1018,1104,544,157,27,1,3
2545,0,2024-04-28(일),경로,41880,24,689,1705,1252,1936,2510,...,2109,1616,1289,905,473,216,35,8,6,14
2546,0,0,국가유공자,598,0,10,17,12,28,42,...,40,26,29,14,8,5,1,0,0,0
2547,0,0,어린이,5636,0,4,4,30,143,303,...,381,241,152,97,63,6,0,0,0,0
2548,0,0,외국인,1456,0,3,2,3,29,66,...,125,114,83,64,58,34,0,0,0,0
2549,0,0,일반인,350374,659,2592,4050,5042,8416,10921,...,21566,15937,13289,12741,10373,6100,1651,254,156,165
2550,0,0,장애인,7503,17,112,204,220,337,445,...,417,312,238,172,144,68,14,1,2,0
2551,0,0,청소년,22591,13,48,51,141,398,718,...,1490,1068,849,824,790,337,92,13,3,0
2552,강동구,2024-04-15(월),경로,31130,78,974,1340,1860,2250,2781,...,1847,1298,907,678,382,144,41,5,1,2
2553,0,0,국가유공자,1412,2,19,32,51,64,132,...,32,34,26,16,15,6,0,0,0,0

In [96]:
# 엑셀에서 데이터 프레임으로 변환하는 과정에서 시군구, 일의 데이터의 경우 처음 등장하는 데이터를 제외하고 아래는 모두 0으로 처리되었다
# EX) 강남구 데이터 100개 중 처음 등장하는 1개만 시군구 = "강남구"이고 나머지는 0으로 처리
# 따라서 0인 시군구 값는 NAN으로 처리 후 NAN이 아닌 데이터 중 바로 위의 값으로 대체한다.  

clean_df.loc[:, '시군구'] = clean_df['시군구'].replace(0, pd.NA)  # 0을 NA로 대체
clean_df.loc[:, '시군구'] = clean_df['시군구'].ffill()  # NA를 바로 위의 값으로 대체

clean_df.loc[:, '일'] = clean_df['일'].replace(0, pd.NA)  # 0을 NA로 대체
clean_df.loc[:, '일'] = clean_df['일'].ffill()  # NA를 바로 위의 값으로 대체

In [104]:
clean_df

,시군구,일,이용자유형,총 발생량,04시 발생량,05시 발생량,06시 발생량,07시 발생량,08시 발생량,09시 발생량,...,18시 도착량,19시 도착량,20시 도착량,21시 도착량,22시 도착량,23시 도착량,00시 도착량,01시 도착량,02시 도착량,03시 도착량
2454,강남구,2024-04-15(월),경로,84187,76,915,2182,2305,3235,4411,...,3194,2103,1517,1163,646,282,86,8,9,20
2455,강남구,2024-04-15(월),국가유공자,1275,1,14,50,48,72,76,...,78,46,31,17,16,9,4,1,0,0
2456,강남구,2024-04-15(월),어린이,5913,0,0,13,202,391,20,...,735,498,260,213,247,19,2,0,0,0
2457,강남구,2024-04-15(월),외국인,1661,0,0,1,8,35,38,...,99,132,64,38,58,21,17,1,0,0
2458,강남구,2024-04-15(월),일반인,768109,679,3106,10074,27295,34095,23140,...,49872,33531,18617,15536,13833,7166,2715,439,247,208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166628,중랑구,2022-01-31(월),어린이,666,0,1,0,5,10,25,...,58,33,25,25,8,9,1,0,0,0
166629,중랑구,2022-01-31(월),외국인,15,0,2,0,1,1,0,...,0,0,0,0,1,0,0,0,0,0
166630,중랑구,2022-01-31(월),일반인,63378,348,989,1432,2218,2863,3623,...,4986,3944,3459,4857,3192,1595,424,45,16,15
166631,중랑구,2022-01-31(월),장애인,1628,1,76,43,47,59,100,...,102,84,65,60,45,25,2,0,0,0
166632,중랑구,2022-01-31(월),청소년,2329,0,4,15,21,64,85,...,205,193,142,206,149,72,9,0,0,0

In [107]:
# 크롤링 중 오류로 
final_data = clean_df.drop_duplicates()

In [108]:
final_data

,시군구,일,이용자유형,총 발생량,04시 발생량,05시 발생량,06시 발생량,07시 발생량,08시 발생량,09시 발생량,...,18시 도착량,19시 도착량,20시 도착량,21시 도착량,22시 도착량,23시 도착량,00시 도착량,01시 도착량,02시 도착량,03시 도착량
2454,강남구,2024-04-15(월),경로,84187,76,915,2182,2305,3235,4411,...,3194,2103,1517,1163,646,282,86,8,9,20
2455,강남구,2024-04-15(월),국가유공자,1275,1,14,50,48,72,76,...,78,46,31,17,16,9,4,1,0,0
2456,강남구,2024-04-15(월),어린이,5913,0,0,13,202,391,20,...,735,498,260,213,247,19,2,0,0,0
2457,강남구,2024-04-15(월),외국인,1661,0,0,1,8,35,38,...,99,132,64,38,58,21,17,1,0,0
2458,강남구,2024-04-15(월),일반인,768109,679,3106,10074,27295,34095,23140,...,49872,33531,18617,15536,13833,7166,2715,439,247,208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166628,중랑구,2022-01-31(월),어린이,666,0,1,0,5,10,25,...,58,33,25,25,8,9,1,0,0,0
166629,중랑구,2022-01-31(월),외국인,15,0,2,0,1,1,0,...,0,0,0,0,1,0,0,0,0,0
166630,중랑구,2022-01-31(월),일반인,63378,348,989,1432,2218,2863,3623,...,4986,3944,3459,4857,3192,1595,424,45,16,15
166631,중랑구,2022-01-31(월),장애인,1628,1,76,43,47,59,100,...,102,84,65,60,45,25,2,0,0,0
166632,중랑구,2022-01-31(월),청소년,2329,0,4,15,21,64,85,...,205,193,142,206,149,72,9,0,0,0

In [120]:
final_data.columns

Index(['시군구', '일', '이용자유형', '총 발생량', '04시 발생량', '05시 발생량', '06시 발생량',
       '07시 발생량', '08시 발생량', '09시 발생량', '10시 발생량', '11시 발생량', '12시 발생량',
       '13시 발생량', '14시 발생량', '15시 발생량', '16시 발생량', '17시 발생량', '18시 발생량',
       '19시 발생량', '20시 발생량', '21시 발생량', '22시 발생량', '23시 발생량', '00시 발생량',
       '01시 발생량', '02시 발생량', '03시 발생량', '총 도착량', '04시 도착량', '05시 도착량',
       '06시 도착량', '07시 도착량', '08시 도착량', '09시 도착량', '10시 도착량', '11시 도착량',
       '12시 도착량', '13시 도착량', '14시 도착량', '15시 도착량', '16시 도착량', '17시 도착량',
       '18시 도착량', '19시 도착량', '20시 도착량', '21시 도착량', '22시 도착량', '23시 도착량',
       '00시 도착량', '01시 도착량', '02시 도착량', '03시 도착량'],
      dtype='object')

In [119]:
final_data = final_data.sort_values(by = ['일', '시군구', '이용자유형'], inplace= True)[:50]

TypeError: 'NoneType' object is not subscriptable

In [118]:
final_data

,시군구,일,이용자유형,총 발생량,04시 발생량,05시 발생량,06시 발생량,07시 발생량,08시 발생량,09시 발생량,...,18시 도착량,19시 도착량,20시 도착량,21시 도착량,22시 도착량,23시 도착량,00시 도착량,01시 도착량,02시 도착량,03시 도착량
161203,강남구,2022-01-01(토),경로,16788,6,426,1109,509,632,781,...,776,530,435,338,182,53,7,0,0,0
161204,강남구,2022-01-01(토),국가유공자,356,1,8,19,13,7,10,...,21,8,14,7,6,1,1,0,0,0
161205,강남구,2022-01-01(토),어린이,1973,0,3,9,9,26,50,...,118,96,58,44,26,5,0,0,0,0
161206,강남구,2022-01-01(토),외국인,126,0,0,0,2,1,2,...,12,6,2,9,4,0,0,0,0,0
161207,강남구,2022-01-01(토),일반인,189999,230,1396,2454,2927,4465,5065,...,12315,7573,6235,9283,5716,2156,403,78,40,22
161208,강남구,2022-01-01(토),장애인,3002,2,72,111,103,96,123,...,154,109,83,95,53,20,7,0,0,0
161209,강남구,2022-01-01(토),청소년,19136,10,37,93,149,275,346,...,1351,686,453,880,941,173,29,3,0,0
161301,강동구,2022-01-01(토),경로,7795,3,372,313,253,390,512,...,539,370,258,285,130,47,2,0,0,0
161302,강동구,2022-01-01(토),국가유공자,275,3,10,9,2,14,19,...,11,6,7,7,2,3,1,0,0,0
161303,강동구,2022-01-01(토),어린이,712,0,4,10,5,4,18,...,79,49,36,31,20,2,2,0,0,0
161304,강동구,2022-01-01(토),외국인,20,0,1,0,2,3,2,...,3,1,0,2,0,0,0,0,0,0
161305,강동구,2022-01-01(토),일반인,62110,183,1055,1751,2005,2764,3250,...,5074,3794,3748,6021,4107,1683,403,39,19,14
161306,강동구,2022-01-01(토),장애인,1423,2,64,53,70,77,76,...,94,59,57,56,30,19,1,0,0,0
161307,강동구,2022-01-01(토),청소년,4867,11,48,69,54,88,160,...,476,391,290,470,404,145,28,1,0,2
161399,강북구,2022-01-01(토),경로,9555,2,282,286,286,406,597,...,582,418,299,265,133,56,0,0,0,0
161400,강북구,2022-01-01(토),국가유공자,302,1,3,13,7,13,16,...,11,5,4,4,1,1,2,0,0,0
161401,강북구,2022-01-01(토),어린이,926,1,1,1,3,6,27,...,81,49,24,31,9,6,1,1,0,0
161402,강북구,2022-01-01(토),외국인,9,0,0,0,1,2,0,...,0,0,0,2,1,0,0,0,0,0
161403,강북구,2022-01-01(토),일반인,79447,442,1369,1852,2195,3199,4077,...,6334,4555,4171,5912,4018,1766,417,103,17,33
161404,강북구,2022-01-01(토),장애인,1851,1,48,58,75,59,106,...,110,97,77,87,52,22,0,0,0,0
161405,강북구,2022-01-01(토),청소년,5303,6,41,73,36,120,156,...,475,341,313,461,331,127,15,3,0,0
161497,강서구,2022-01-01(토),경로,12809,5,576,486,387,602,885,...,805,608,433,357,244,104,5,0,0,0
161498,강서구,2022-01-01(토),국가유공자,298,5,2,9,9,11,10,...,19,9,7,6,2,1,0,0,0,0
161499,강서구,2022-01-01(토),어린이,1468,0,3,5,8,19,31,...,118,74,51,52,25,4,0,0,0,0
161500,강서구,2022-01-01(토),외국인,20,0,0,1,0,1,2,...,2,1,2,1,0,0,0,0,0,0
161501,강서구,2022-01-01(토),일반인,123502,333,1675,2463,3066,4871,5969,...,9532,7289,6579,9875,6717,2870,468,63,39,47
161502,강서구,2022-01-01(토),장애인,3147,2,125,108,104,156,205,...,202,157,117,138,89,39,1,0,0,0
161503,강서구,2022-01-01(토),청소년,8092,8,34,96,87,226,259,...,803,497,450,647,547,198,26,2,0,1
161595,관악구,2022-01-01(토),경로,8376,18,414,361,289,384,527,...,472,405,307,299,136,51,4,0,0,0
161596,관악구,2022-01-01(토),국가유공자,328,2,9,13,10,9,14,...,21,13,4,6,0,3,0,0,0,0
161597,관악구,2022-01-01(토),어린이,928,2,2,0,0,11,23,...,81,64,35,21,8,5,0,0,0,0
161598,관악구,2022-01-01(토),외국인,51,0,4,2,1,3,5,...,0,6,0,4,6,0,0,0,0,0
161599,관악구,2022-01-01(토),일반인,139162,322,2171,3294,3758,6025,8044,...,11264,9178,8467,13361,8451,3813,510,50,43,41
161600,관악구,2022-01-01(토),장애인,1797,4,65,64,68,69,78,...,129,114,93,112,58,24,1,0,0,0
161601,관악구,2022-01-01(토),청소년,6318,16,54,81,78,113,251,...,545,419,354,513,403,158,15,0,0,1
161693,광진구,2022-01-01(토),경로,8790,2,301,314,264,450,563,...,540,342,240,233,122,42,1,0,0,0
161694,광진구,2022-01-01(토),국가유공자,194,1,2,7,8,7,11,...,11,5,3,6,4,0,0,0,0,0
161695,광진구,2022-01-01(토),어린이,914,0,0,2,3,15,27,...,86,46,29,27,11,4,0,0,0,0
161696,광진구,2022-01-01(토),외국인,47,1,1,2,2,2,3,...,5,10,4,3,3,0,0,0,0,0
161697,광진구,2022-01-01(토),일반인,100634,180,984,1963,2326,4732,5301,...,7975,5596,5071,7804,4926,2037,316,63,34,22
161698,광진구,2022-01-01(토),장애인,2005,1,63,60,49,98,117,...,132,77,73,84,36,18,4,0,0,0
161699,광진구,2022-01-01(토),청소년,7240,3,26,60,69,289,225,...,654,389,311,461,270,104,11,3,1,0
161791,구로구,2022-01-01(토),경로,11695,54,561,468,415,521,750,...,759,486,360,336,193,53,7,0,0,0
161792,구로구,2022-01-01(토),국가유공자,300,2,14,15,4,9,12,...,17,5,2,4,6,2,1,0,0,0
161793,구로구,2022-01-01(토),어린이,888,0,1,2,3,8,49,...,99,54,49,27,19,4,0,0,0,0
161794,구로구,2022-01-01(토),외국인,138,0,1,5,2,14,12,...,9,7,7,13,4,1,0,0,0,0
161795,구로구,2022-01-01(토),일반인,101517,335,1497,2170,2906,4712,5716,...,7826,6189,5807,9133,5767,2507,478,39,30,16
161796,구로구,2022-01-01(토),장애인,2457,3,83,81,79,97,145,...,184,129,109,118,83,29,5,0,0,0
161797,구로구,2022-01-01(토),청소년,5117,5,27,68,53,96,150,...,471,418,364,529,428,155,27,2,1,0
161889,금천구,2022-01-01(토),경로,2371,3,90,93,108,98,146,...,151,89,63,51,22,9,0,0,0,0

In [128]:
final_data.to_csv('목적 통행량 데이터.csv', index=False)

In [127]:
final_data

,시군구,일,이용자유형,총 발생량,04시 발생량,05시 발생량,06시 발생량,07시 발생량,08시 발생량,09시 발생량,...,18시 도착량,19시 도착량,20시 도착량,21시 도착량,22시 도착량,23시 도착량,00시 도착량,01시 도착량,02시 도착량,03시 도착량
161203,강남구,2022-01-01(토),경로,16788,6,426,1109,509,632,781,...,776,530,435,338,182,53,7,0,0,0
161204,강남구,2022-01-01(토),국가유공자,356,1,8,19,13,7,10,...,21,8,14,7,6,1,1,0,0,0
161205,강남구,2022-01-01(토),어린이,1973,0,3,9,9,26,50,...,118,96,58,44,26,5,0,0,0,0
161206,강남구,2022-01-01(토),외국인,126,0,0,0,2,1,2,...,12,6,2,9,4,0,0,0,0,0
161207,강남구,2022-01-01(토),일반인,189999,230,1396,2454,2927,4465,5065,...,12315,7573,6235,9283,5716,2156,403,78,40,22
161208,강남구,2022-01-01(토),장애인,3002,2,72,111,103,96,123,...,154,109,83,95,53,20,7,0,0,0
161209,강남구,2022-01-01(토),청소년,19136,10,37,93,149,275,346,...,1351,686,453,880,941,173,29,3,0,0
161301,강동구,2022-01-01(토),경로,7795,3,372,313,253,390,512,...,539,370,258,285,130,47,2,0,0,0
161302,강동구,2022-01-01(토),국가유공자,275,3,10,9,2,14,19,...,11,6,7,7,2,3,1,0,0,0
161303,강동구,2022-01-01(토),어린이,712,0,4,10,5,4,18,...,79,49,36,31,20,2,2,0,0,0
161304,강동구,2022-01-01(토),외국인,20,0,1,0,2,3,2,...,3,1,0,2,0,0,0,0,0,0
161305,강동구,2022-01-01(토),일반인,62110,183,1055,1751,2005,2764,3250,...,5074,3794,3748,6021,4107,1683,403,39,19,14
161306,강동구,2022-01-01(토),장애인,1423,2,64,53,70,77,76,...,94,59,57,56,30,19,1,0,0,0
161307,강동구,2022-01-01(토),청소년,4867,11,48,69,54,88,160,...,476,391,290,470,404,145,28,1,0,2
161399,강북구,2022-01-01(토),경로,9555,2,282,286,286,406,597,...,582,418,299,265,133,56,0,0,0,0
161400,강북구,2022-01-01(토),국가유공자,302,1,3,13,7,13,16,...,11,5,4,4,1,1,2,0,0,0
161401,강북구,2022-01-01(토),어린이,926,1,1,1,3,6,27,...,81,49,24,31,9,6,1,1,0,0
161402,강북구,2022-01-01(토),외국인,9,0,0,0,1,2,0,...,0,0,0,2,1,0,0,0,0,0
161403,강북구,2022-01-01(토),일반인,79447,442,1369,1852,2195,3199,4077,...,6334,4555,4171,5912,4018,1766,417,103,17,33
161404,강북구,2022-01-01(토),장애인,1851,1,48,58,75,59,106,...,110,97,77,87,52,22,0,0,0,0
161405,강북구,2022-01-01(토),청소년,5303,6,41,73,36,120,156,...,475,341,313,461,331,127,15,3,0,0
161497,강서구,2022-01-01(토),경로,12809,5,576,486,387,602,885,...,805,608,433,357,244,104,5,0,0,0
161498,강서구,2022-01-01(토),국가유공자,298,5,2,9,9,11,10,...,19,9,7,6,2,1,0,0,0,0
161499,강서구,2022-01-01(토),어린이,1468,0,3,5,8,19,31,...,118,74,51,52,25,4,0,0,0,0
161500,강서구,2022-01-01(토),외국인,20,0,0,1,0,1,2,...,2,1,2,1,0,0,0,0,0,0
161501,강서구,2022-01-01(토),일반인,123502,333,1675,2463,3066,4871,5969,...,9532,7289,6579,9875,6717,2870,468,63,39,47
161502,강서구,2022-01-01(토),장애인,3147,2,125,108,104,156,205,...,202,157,117,138,89,39,1,0,0,0
161503,강서구,2022-01-01(토),청소년,8092,8,34,96,87,226,259,...,803,497,450,647,547,198,26,2,0,1
161595,관악구,2022-01-01(토),경로,8376,18,414,361,289,384,527,...,472,405,307,299,136,51,4,0,0,0
161596,관악구,2022-01-01(토),국가유공자,328,2,9,13,10,9,14,...,21,13,4,6,0,3,0,0,0,0
161597,관악구,2022-01-01(토),어린이,928,2,2,0,0,11,23,...,81,64,35,21,8,5,0,0,0,0
161598,관악구,2022-01-01(토),외국인,51,0,4,2,1,3,5,...,0,6,0,4,6,0,0,0,0,0
161599,관악구,2022-01-01(토),일반인,139162,322,2171,3294,3758,6025,8044,...,11264,9178,8467,13361,8451,3813,510,50,43,41
161600,관악구,2022-01-01(토),장애인,1797,4,65,64,68,69,78,...,129,114,93,112,58,24,1,0,0,0
161601,관악구,2022-01-01(토),청소년,6318,16,54,81,78,113,251,...,545,419,354,513,403,158,15,0,0,1
161693,광진구,2022-01-01(토),경로,8790,2,301,314,264,450,563,...,540,342,240,233,122,42,1,0,0,0
161694,광진구,2022-01-01(토),국가유공자,194,1,2,7,8,7,11,...,11,5,3,6,4,0,0,0,0,0
161695,광진구,2022-01-01(토),어린이,914,0,0,2,3,15,27,...,86,46,29,27,11,4,0,0,0,0
161696,광진구,2022-01-01(토),외국인,47,1,1,2,2,2,3,...,5,10,4,3,3,0,0,0,0,0
161697,광진구,2022-01-01(토),일반인,100634,180,984,1963,2326,4732,5301,...,7975,5596,5071,7804,4926,2037,316,63,34,22
161698,광진구,2022-01-01(토),장애인,2005,1,63,60,49,98,117,...,132,77,73,84,36,18,4,0,0,0
161699,광진구,2022-01-01(토),청소년,7240,3,26,60,69,289,225,...,654,389,311,461,270,104,11,3,1,0
161791,구로구,2022-01-01(토),경로,11695,54,561,468,415,521,750,...,759,486,360,336,193,53,7,0,0,0
161792,구로구,2022-01-01(토),국가유공자,300,2,14,15,4,9,12,...,17,5,2,4,6,2,1,0,0,0
161793,구로구,2022-01-01(토),어린이,888,0,1,2,3,8,49,...,99,54,49,27,19,4,0,0,0,0
161794,구로구,2022-01-01(토),외국인,138,0,1,5,2,14,12,...,9,7,7,13,4,1,0,0,0,0
161795,구로구,2022-01-01(토),일반인,101517,335,1497,2170,2906,4712,5716,...,7826,6189,5807,9133,5767,2507,478,39,30,16
161796,구로구,2022-01-01(토),장애인,2457,3,83,81,79,97,145,...,184,129,109,118,83,29,5,0,0,0
161797,구로구,2022-01-01(토),청소년,5117,5,27,68,53,96,150,...,471,418,364,529,428,155,27,2,1,0
161889,금천구,2022-01-01(토),경로,2371,3,90,93,108,98,146,...,151,89,63,51,22,9,0,0,0,0

In [61]:
df

,시간대:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,합계,04,05,06,07,...,Unnamed: 36,Unnamed: 38,Unnamed: 40,Unnamed: 42,Unnamed: 44,Unnamed: 46,Unnamed: 48,Unnamed: 50,Unnamed: 52,Unnamed: 54
2452,시도코드,시도,시군구,일,이용자유형,발생량,발생량,발생량,발생량,발생량,...,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량,도착량
2453,합계,0,0,0,0,114284606,368328,1565950,3060455,7517612,...,9907629,7500880,4900361,4349626,4014120,2411732,858761,130804,62462,53811
2454,11,서울특별시,강남구,2024-04-15(월),경로,84187,76,915,2182,2305,...,3194,2103,1517,1163,646,282,86,8,9,20
2455,0,0,0,0,국가유공자,1275,1,14,50,48,...,78,46,31,17,16,9,4,1,0,0
2456,0,0,0,0,어린이,5913,0,0,13,202,...,735,498,260,213,247,19,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166628,0,0,0,0,어린이,666,0,1,0,5,...,58,33,25,25,8,9,1,0,0,0
166629,0,0,0,0,외국인,15,0,2,0,1,...,0,0,0,0,1,0,0,0,0,0
166630,0,0,0,0,일반인,63378,348,989,1432,2218,...,4986,3944,3459,4857,3192,1595,424,45,16,15
166631,0,0,0,0,장애인,1628,1,76,43,47,...,102,84,65,60,45,25,2,0,0,0
166632,0,0,0,0,청소년,2329,0,4,15,21,...,205,193,142,206,149,72,9,0,0,0

In [39]:
column_list = list(df.columns)
column_list

['시간대:',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 '합계',
 'Unnamed: 7',
 '04',
 'Unnamed: 9',
 '05',
 'Unnamed: 11',
 '06',
 'Unnamed: 13',
 '07',
 'Unnamed: 15',
 '08',
 'Unnamed: 17',
 '09',
 'Unnamed: 19',
 10,
 'Unnamed: 21',
 11,
 'Unnamed: 23',
 12,
 'Unnamed: 25',
 13,
 'Unnamed: 27',
 14,
 'Unnamed: 29',
 15,
 'Unnamed: 31',
 16,
 'Unnamed: 33',
 17,
 'Unnamed: 35',
 18,
 'Unnamed: 37',
 19,
 'Unnamed: 39',
 20,
 'Unnamed: 41',
 21,
 'Unnamed: 43',
 22,
 'Unnamed: 45',
 23,
 'Unnamed: 47',
 '00',
 'Unnamed: 49',
 '01',
 'Unnamed: 51',
 '02',
 'Unnamed: 53',
 '03',
 'Unnamed: 55',
 'Unnamed: 6',
 'Unnamed: 8',
 'Unnamed: 10',
 'Unnamed: 12',
 'Unnamed: 14',
 'Unnamed: 16',
 'Unnamed: 18',
 'Unnamed: 20',
 'Unnamed: 22',
 'Unnamed: 24',
 'Unnamed: 26',
 'Unnamed: 28',
 'Unnamed: 30',
 'Unnamed: 32',
 'Unnamed: 34',
 'Unnamed: 36',
 'Unnamed: 38',
 'Unnamed: 40',
 'Unnamed: 42',
 'Unnamed: 44',
 'Unnamed: 46',
 'Unnamed: 48',
 'Unnamed: 50',
 'Unnamed: 52',
 'Unnamed: 54']

In [16]:
base_path = "C:\\Users\\MASTER\\Desktop\\교통데이터"
for i in range(89):
    file_path = base_path + f"\\이용량 지표(목적통행량)_20240513 ({i}).xlsx"

In [17]:
file_path1 = base_path + f"\\이용량 지표(목적통행량)_20240513 (10).xlsx"

In [8]:
file_path2 = base_path + f"\\이용량 지표(목적통행량)_20240513 (60).xlsx"

In [18]:
data_1 = pd.read_excel(file_path1)

In [11]:
data_1

,시간대:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,합계,Unnamed: 6,04,Unnamed: 8,05,...,23,Unnamed: 46,00,Unnamed: 48,01,Unnamed: 50,02,Unnamed: 52,03,Unnamed: 54
0,시도코드,시도,시군구,일,이용자유형,발생량,도착량,발생량,도착량,발생량,...,발생량,도착량,발생량,도착량,발생량,도착량,발생량,도착량,발생량,도착량
1,합계,0,0,0,0,24948063,24688357,87901,36665,350255,...,355322,470691,80878,170737,14661,23125,10211,10924,9301,9639
2,11,서울특별시,강남구,2024-01-29(월),경로,83750,81835,64,89,924,...,258,256,50,84,7,9,7,11,6,17
3,0,0,0,0,국가유공자,1291,1269,1,0,13,...,5,11,1,1,1,0,0,0,1,0
4,0,0,0,0,어린이,6048,5885,1,0,1,...,9,10,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,0,0,0,0,어린이,1549,1498,1,0,1,...,0,1,0,0,0,0,0,0,0,0
523,0,0,0,0,외국인,6,8,0,0,0,...,0,0,0,0,0,0,0,0,0,0
524,0,0,0,0,일반인,157073,151334,1477,339,3690,...,1571,5219,472,2023,140,363,106,169,89,165
525,0,0,0,0,장애인,8228,8068,90,14,269,...,32,90,10,21,0,3,6,5,0,1
526,0,0,0,0,청소년,6636,6481,9,5,16,...,96,198,39,87,5,17,4,6,0,1

In [15]:
data_2[:10]

,시간대:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,합계,Unnamed: 6,04,Unnamed: 8,05,...,23,Unnamed: 46,00,Unnamed: 48,01,Unnamed: 50,02,Unnamed: 52,03,Unnamed: 54
0,시도코드,시도,시군구,일,이용자유형,발생량,도착량,발생량,도착량,발생량,...,발생량,도착량,발생량,도착량,발생량,도착량,발생량,도착량,발생량,도착량
1,합계,0,0,0,0,107706389,106361434,340949,138930,1464112,...,1597479,2124376,466821,814099,71126,118216,36533,42372,32535,31763
2,11,서울특별시,강남구,2022-11-15(화),경로,74933,72362,27,0,859,...,173,215,36,72,0,2,0,0,0,0
3,0,0,0,0,국가유공자,1223,1046,6,1,14,...,10,5,4,1,2,0,1,0,0,0
4,0,0,0,0,어린이,4813,4698,1,0,2,...,6,4,1,1,0,0,0,0,0,0
5,0,0,0,0,외국인,908,897,0,0,3,...,7,14,0,4,0,0,0,0,0,0
6,0,0,0,0,일반인,780453,791584,729,659,3188,...,15074,7573,3240,2763,436,447,243,207,218,245
7,0,0,0,0,장애인,11048,10776,6,0,104,...,77,66,16,22,0,2,0,0,0,0
8,0,0,0,0,청소년,26298,24943,2,1,19,...,372,292,52,56,4,3,0,0,0,0
9,0,0,0,2022-11-16(수),경로,73925,71403,23,0,876,...,197,255,25,55,0,3,0,0,0,0

In [10]:
data_1

,시간대:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,합계,Unnamed: 6,04,Unnamed: 8,05,...,23,Unnamed: 46,00,Unnamed: 48,01,Unnamed: 50,02,Unnamed: 52,03,Unnamed: 54
0,시도코드,시도,시군구,일,이용자유형,발생량,도착량,발생량,도착량,발생량,...,발생량,도착량,발생량,도착량,발생량,도착량,발생량,도착량,발생량,도착량
1,합계,0,0,0,0,24948063,24688357,87901,36665,350255,...,355322,470691,80878,170737,14661,23125,10211,10924,9301,9639
2,11,서울특별시,강남구,2024-01-29(월),경로,83750,81835,64,89,924,...,258,256,50,84,7,9,7,11,6,17
3,0,0,0,0,국가유공자,1291,1269,1,0,13,...,5,11,1,1,1,0,0,0,1,0
4,0,0,0,0,어린이,6048,5885,1,0,1,...,9,10,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,0,0,0,0,어린이,1549,1498,1,0,1,...,0,1,0,0,0,0,0,0,0,0
523,0,0,0,0,외국인,6,8,0,0,0,...,0,0,0,0,0,0,0,0,0,0
524,0,0,0,0,일반인,157073,151334,1477,339,3690,...,1571,5219,472,2023,140,363,106,169,89,165
525,0,0,0,0,장애인,8228,8068,90,14,269,...,32,90,10,21,0,3,6,5,0,1
526,0,0,0,0,청소년,6636,6481,9,5,16,...,96,198,39,87,5,17,4,6,0,1

In [34]:
df_combined.to_csv('combined_file.csv', index=False)

In [35]:
df_combined

,시간대:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,합계,Unnamed: 7,04,Unnamed: 9,...,Unnamed: 36,Unnamed: 38,Unnamed: 40,Unnamed: 42,Unnamed: 44,Unnamed: 46,Unnamed: 48,Unnamed: 50,Unnamed: 52,Unnamed: 54
0,시도코드,시도,시군구,일,기상,이용자유형,발생량,도착량,발생량,도착량,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,합계,0,0,0,0,0,113734294,112369186,354604,151700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,서울특별시,강남구,2024-04-01(월),맑음,경로,87364,85583,60,101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0,0,0,0,국가유공자,1348,1338,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0,0,0,0,어린이,6443,6266,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158744,0,0,0,0,어린이,NaN,1382,NaN,0,NaN,...,114,77,55,22,7,6,0,0,0,0
158745,0,0,0,0,외국인,NaN,16,NaN,0,NaN,...,1,0,1,1,2,0,0,0,0,0
158746,0,0,0,0,일반인,NaN,148005,NaN,1480,NaN,...,18420,16797,9637,7822,7504,5610,1473,210,99,62
158747,0,0,0,0,장애인,NaN,3577,NaN,6,NaN,...,372,249,127,112,79,69,8,0,0,0
158748,0,0,0,0,청소년,NaN,10220,NaN,0,NaN,...,707,490,406,441,629,215,42,6,2,0

In [10]:
df_combined = pd.concat([pd.read_excel(fp) for fp in file_paths], ignore_index=True)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/MASTER/Downloads/이용량 지표(목적통행량)_20240513 (0)'

In [ ]:
df_combined.to_csv('temporary_data.csv', index= False)